name: Android Build

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-20.04
    
    steps:

    - name: max
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-docker-images: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Checkout code
      uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        echo "Free space:"
        df -h
        sudo apt-get update
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
        sudo apt-get install -y python2.7 python2.7-dev
        sudo apt autoremove -y
        sudo apt autoclean -y
        sudo apt clean -y
        echo "Free space:"
        df -h

    - name: Set up Java 
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Verify Java installation
      run: |
        echo "Java version:"
        java -version
        echo "\nJAVA_HOME path:"
        echo $JAVA_HOME

    # - uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.13'

    - name: Install Repo
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "PATH=$PATH:~/bin" >> $GITHUB_PATH
        
    - name: Sync Android source
      run: |
        repo init --partial-clone -b android-8.0.0_r51 -u https://android.googlesource.com/platform/manifest -m default.xml
        repo sync -c -j8 --no-tags --no-clone-bundle --current-branch
        
    - name: Build Android
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}
      run: |
        python2.7 -m pip install virtualenv
        python2.7 -m venv venv
        source venv/bin/activate
        . build/envsetup.sh
        lunch aosp_arm64
        make -j$(nproc --all)
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-image
        path: |
          out/target/product/aosp_cf_x86_64_phone/system.img
          out/target/product/aosp_cf_x86_64_phone/boot.img
          out/target/product/aosp_arm64/system.img
          out/target/product/aosp_arm64/boot.img
          out/target/product/*/*.img
          